name: Turn Pages on
on:
  create

jobs:
  callPagesApi:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: POST /repos/${{ github.repository }}/pages/builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
